class utilsError(Exception): ...
class ImportPermissionError(utilsError):
  def __init__(self, name: str) -> None:
    super().__init__(f"Você não tem permissão para importar essa lib!")
    self.name: str = name
class GuildNotExists(utilsError):
  def __init__(self, Guild: object, *args, **kwgs) -> None:
    super().__init__(f"Guild {Guild.id} not exists!")
class GuildAlreadyExists(utilsError):
  def __init__(self, Guild: object) -> None:
    super().__init__(f"Guild {Guild.id} already exists!")
class HabilityNotExists(utilsError): ...
class FamilyNotExists(utilsError): ...
class UserNotExists(utilsError): ...
class UserAlreadyExists(utilsError): ...
class PlayerNotExists(utilsError): ...
class ResponseError(utilsError):
  def __init__(self, message: str) -> None:
    super().__init__(message)

class ArgumentTypeNotSupported(utilsError): ...
class NotChoices(utilsError): ...